imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@BackendBundle/Resources/config/services.yml" }
    - { resource: "@EditorBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
        gc_maxlifetime: 7200
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        currency: '%currency%'
        site_title: '%site_title%'
        ticket_link: '%ticket_link%'
        flowww_link: '%flowww_link%'
        image_path: "%app.path.images%"
        image_complete_path: "%kernel.root_dir%/../web/uploads/images"
        files_path: "%app.path.files%"
        files_complete_path: "%kernel.root_dir%/../web/uploads/files"
        registration_path: "%app.path.registrations%"
        registration_complete_path: "%kernel.root_dir%/../web/uploads/registrations"
        document_path: "%app.path.documents%"
        document_complete_path: "%kernel.root_dir%/../web/uploads/documents"
        creativity_path: "%app.path.creativities%"
        creativity_complete_path: "%kernel.root_dir%/../web/uploads/creativities"
        creativity_raw_path: "%app.path.creativities_raw%"
        creativity_raw_complete_path: "%kernel.root_dir%/../web/uploads/creativities-raw"
        proposal_path: "%app.path.proposals%"
        proposal_complete_path: "%kernel.root_dir%/../web/uploads/proposals"
        creativity_oder_path: "%app.path.creativity_orders%"
        creativity_oder_complete_path: "%kernel.root_dir%/../web/uploads/creativity_orders"
        url_map: '%url_map%'
    form:
        resources:
            - 'BackendBundle::bootstrap_3_layout.html.twig'
            - 'BackendBundle:Form:autocomplete.html.twig'
            - 'BackendBundle:Form:date_picker.html.twig'
            - 'BackendBundle:Form:files.html.twig'
            - 'BackendBundle:Form:document.html.twig'
            - 'BackendBundle:Form:map.html.twig'
            - 'BackendBundle:Form:location.html.twig'
            - 'BackendBundle:Form:ckeditor.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                strtodate: DoctrineExtensions\Query\Mysql\StrToDate
                dateformat: DoctrineExtensions\Query\Mysql\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: ../Resources/node_modules/.bin/uglifycjs
        uglifycss:
            bin: ../Resources/node_modules/.bin/uglifycss

# Vich Uploader Configuration
vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix:         "%app.path.images%"
            upload_destination: "%kernel.root_dir%/../web/uploads/images"
        files:
            uri_prefix:         "%app.path.files%"
            upload_destination: "%kernel.root_dir%/../web/uploads/files"
        documents:
            uri_prefix:         "%app.path.documents%"
            upload_destination: "%kernel.root_dir%/../web/uploads/documents"
        creativities:
            uri_prefix:         "%app.path.creativities%"
            upload_destination: "%kernel.root_dir%/../web/uploads/creativities"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        creativities_raw:
            uri_prefix:         "%app.path.creativities_raw%"
            upload_destination: "%kernel.root_dir%/../web/uploads/creativities-raw"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        proposals:
            uri_prefix:         "%app.path.proposals%"
            upload_destination: "%kernel.root_dir%/../web/uploads/proposals"
        creativity_orders:
            uri_prefix:         "%app.path.creativity_orders%"
            upload_destination: "%kernel.root_dir%/../web/uploads/creativity_orders"
        templates:
            uri_prefix:         "%app.path.templates%"
            upload_destination: "%kernel.root_dir%/../web/uploads/templates"

# Knp Paginator Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        # KnpPaginatorBundle:Pagination:sliding.html.twig (by default)
        # KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        #KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            blameable: trueƒ