# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_CLIENT, ROLE_ALLOWED_TO_SWITCH]
    encoders:
        AppBundle\Entity\Client: { algorithm: sha512, iterations: 10 }

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity: { class: AppBundle\Entity\Client, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/*
            provider:  main
            anonymous: true
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: admin_client_list
            logout:
                path:   logout
                target: login
            remember_me:
                secret: "%secret%"
                lifetime: 3600
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
    access_control:
          - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/ajax/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/candidatos, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/multimedia/list, roles: ROLE_CLIENT }
          - { path: ^/admin/registration/list, roles: ROLE_CLIENT }
          - { path: ^/admin/press-release$, roles: ROLE_CLIENT }
          - { path: ^/admin/creativity-proposal/new$, roles: ROLE_CLIENT }
          - { path: ^/admin/registration/$, roles: ROLE_ADMIN }
          - { path: ^/admin/creativity/$, roles: ROLE_ADMIN }
          - { path: ^/admin/creativity-proposal/$, roles: ROLE_ADMIN }
          - { path: ^/admin/multimedia/$, roles: ROLE_ADMIN }
          - { path: ^/admin, roles: ROLE_CLIENT }
            # activate different ways to authenticate%
