services:
    webapp.manager.client_manager:
        class: AppBundle\Model\ClientModel
        arguments: ["@service_container"]
    webapp.manager.plan_manager:
        class: AppBundle\Model\PlanModel
        arguments: ["@service_container"]
    webapp.manager.postalcode_manager:
        class: AppBundle\Model\PostalCodeModel
        arguments: ["@service_container"]
    webapp.manager.country_manager:
        class: AppBundle\Model\CountryModel
        arguments: ["@service_container"]
    webapp.manager.province_manager:
        class: AppBundle\Model\ProvinceModel
        arguments: ["@service_container"]
    webapp.manager.city_manager:
        class: AppBundle\Model\CityModel
        arguments: ["@service_container"]
    webapp.manager.multimedia_manager:
        class: AppBundle\Model\MultimediaModel
        arguments: ["@service_container"]
    webapp.manager.multimedia_category_manager:
        class: AppBundle\Model\MultimediaCategoryModel
        arguments: ["@service_container"]
    webapp.manager.academic_manager:
        class: AppBundle\Model\AcademicModel
        arguments: ["@service_container"]
    webapp.listener.login_listener:
        class: AppBundle\EventListener\SecurityListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin, priority: "255" }
    webapp.services.slugify:
        class: AppBundle\Services\Slugify
    webapp.services.formatting:
        class: AppBundle\Services\Formatting
    webapp.twig.client:
        class: AppBundle\Twig\ClientExtension
        arguments: [ "@service_container" ]
        tags:
            - { name: twig.extension }
    webapp.form.filter_multimedia_category:
        class: AppBundle\Form\FilterMultimediaCategory
        arguments: ["@form.factory", "@router", "@webapp.manager.multimedia_category_manager"]