services:
    webapp.manager.client_manager:
        class: AppBundle\Model\ClientModel
        arguments: ["@service_container"]
    webapp.manager.plan_manager:
        class: AppBundle\Model\PlanModel
        arguments: ["@service_container"]